DeployFileWebApp/Controllers/ManageServerController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using DeployFileWebApp.Models;
using Microsoft.Extensions.Options;
using Microsoft.AspNetCore.Http;
using System.IO;
using CommonService;
using DeployFileWebApp.Repository;
using Microsoft.AspNetCore.Hosting;
using DeployFileWebApp.Data;

namespace DeployFileWebApp.Controllers
{
	public class ManageServerController : Controller
	{
		private const string _loginSessionKeyName = "_Username";
		private readonly IDatabaseRepository _databaseRepository;
		public ManageServerController(IDatabaseRepository databaseRepository, IWebHostEnvironment webHostEnvironment)
		{
			_databaseRepository = databaseRepository;
		}

		public IActionResult Index()
		{
            var username = HttpContext.Session.GetString(_loginSessionKeyName);
            if (string.IsNullOrEmpty(username))
            {
                return RedirectToAction("Index", "Login");
            }
			ViewData["IsLogin"] = true;
			var servers = _databaseRepository.GetAllServers();
			return View(servers);
		}

		public IActionResult Sites(int id)
		{
			//var username = HttpContext.Session.GetString(_loginSessionKeyName);
			//if (string.IsNullOrEmpty(username))
			//{
			//	return RedirectToAction("Index", "Login");
			//}
			var sites = _databaseRepository.GetAllSites(id);
			return View(sites);
		}

		[HttpGet]
		public IActionResult GetServers()
		{
			var servers = _databaseRepository.GetAllServers();
			return PartialView("_ServerList", servers);
		}

		[HttpGet]
		public IActionResult SaveServer(int id = 0)
		{
			ServerModel model = new ServerModel();
			try
			{
				if (id != 0)
				{
					var data = _databaseRepository.GetServer(id);
					model = new ServerModel()
					{
						ServerId = data.ServerId,
						ServerName = data.ServerName,
						ServerDesc = data.ServerDesc
					};
				}
				return PartialView(model);
			}
			catch (Exception ex)
			{
				return PartialView(model);
			}
		}

		[HttpPost]
		public IActionResult SaveServer(ServerModel model)
		{
			if (ModelState.IsValid)
			{
				var response = _databaseRepository.SaveServer(model);
				return this.GetJsonResult("Server Saved Successfully");
			}
			else
			{
				return this.GetJsonResult();
			}
		}

		[HttpPost]
		public IActionResult UpdateSite(Servers server)
		{
			var commands = new List<Commands>();
			commands.Add(new Commands
			{
				CommandType = (int)CommandTypes.UpdateSiteList,
				ServerId = server.ServerId,
				SiteId = 0,
				ServerName = server.ServerName,
				ZipPath = string.Empty,
				Status = (int)CommandStatus.Pending,
				CreatedOn = DateTime.Now
			});
			var isSuccess = _databaseRepository.SaveCommand(commands);
			if (isSuccess)
			{
				return this.GetJsonResult("Update site command sent successfully. Please wait for few minutes.");
			}
			return this.GetErrorJsonResult("Please try again later!");
		}
	}
}

DeployFileWebApp/Views/Shared/_Layout.cshtml
@{
    bool isLogin = Convert.ToBoolean(ViewData["IsLogin"]);
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DeployFileWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/juery-multiselect/jquery.lwMultiSelect.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DeployFileWebApp</a>
                @if (isLogin)
                {
                    <a class="navbar-brand" asp-area="" asp-controller="ManageServer" asp-action="Index">Server</a>
                    <a class="" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - DeployFileWebApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/juery-multiselect/jquery.lwMultiSelect.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>